// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using CourierPortal.Core.Domain.Entities;

namespace CourierPortal.Core.Domain
{
    public partial class DespatchContext
    {

        [DbFunction("IdToBatchNo", "dbo")]
        public static string IdToBatchNo(long? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IdToInvoiceNo", "dbo")]
        public static string IdToInvoiceNo(long? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
