// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierScheduleResponse
{
    public long Id { get; set; }

    public long ScheduleId { get; set; }

    public int CourierId { get; set; }

    public int StatusId { get; set; }

    public DateTime? NotificationSent { get; set; }

    public int? NotificationStatusId { get; set; }

    public DateTime Created { get; set; }

    public DateTime Updated { get; set; }

    public long? TimeSlotId { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual CourierScheduleResponseStatus NotificationStatus { get; set; }

    public virtual CourierSchedule Schedule { get; set; }

    public virtual CourierScheduleResponseStatus Status { get; set; }

    public virtual CourierScheduleTimeSlot TimeSlot { get; set; }
}