// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierApplicantUpload
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int ApplicantId { get; set; }

    public int DocumentId { get; set; }

    public string FileName { get; set; }

    public string Type { get; set; }

    public long Length { get; set; }

    public byte[] Data { get; set; }

    public virtual CourierApplicant Applicant { get; set; }

    public virtual CourierApplicantDocument Document { get; set; }
}