// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierInvoiceBatchItem
{
    public long Id { get; set; }

    public long BatchId { get; set; }

    public long InvoiceId { get; set; }

    public DateTime Created { get; set; }

    public virtual CourierInvoiceBatch Batch { get; set; }

    public virtual CourierInvoice Invoice { get; set; }
}