// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierInvoiceLine
{
    public long Id { get; set; }

    public long InvoiceId { get; set; }

    public DateTime Created { get; set; }

    public string Description { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public virtual ICollection<CourierInvoiceLineJobMaster> CourierInvoiceLineJobMasters { get; set; } = new List<CourierInvoiceLineJobMaster>();

    public virtual ICollection<CourierInvoiceLineJob> CourierInvoiceLineJobs { get; set; } = new List<CourierInvoiceLineJob>();

    public virtual CourierInvoice Invoice { get; set; }
}
