// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierDeductionLine
{
    public long Id { get; set; }

    public DateTime Created { get; set; }

    public long DeductionId { get; set; }

    public int DeductionTypeId { get; set; }

    public string Description { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public virtual CourierDeduction Deduction { get; set; }

    public virtual CourierDeductionType DeductionType { get; set; }
}