// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierScheduleTimeSlot
{
    public long Id { get; set; }

    public DateTime Created { get; set; }

    public int? SiteId { get; set; }

    public DateTime BookDateTime { get; set; }

    public int? Wanted { get; set; }

    public int? LocationId { get; set; }

    public virtual ICollection<CourierScheduleResponse> CourierScheduleResponses { get; set; } = new List<CourierScheduleResponse>();

    public virtual ICollection<CourierScheduleTimeSlotVehicleType> CourierScheduleTimeSlotVehicleTypes { get; set; } = new List<CourierScheduleTimeSlotVehicleType>();

    public virtual TblBulkRegion Location { get; set; }
}