// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string OpenforceActivationCode { get; set; }

    public string AccountsId { get; set; }

    public virtual ICollection<CourierApplicant> CourierApplicants { get; set; } = new List<CourierApplicant>();

    public virtual ICollection<TucCourier> TucCouriers { get; set; } = new List<TucCourier>();
}