// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Web.Core.Domain.Despatch;

public partial class CourierInvoice
{
    public long Id { get; set; }

    public DateTime Created { get; set; }

    public int CourierId { get; set; }

    public string TaxNo { get; set; }

    public decimal GstPercentage { get; set; }

    public decimal WithholdingTaxPercentage { get; set; }

    public string Reference { get; set; }

    public string ExternalId { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual ICollection<CourierDeduction> CourierDeductions { get; set; } = new List<CourierDeduction>();

    public virtual ICollection<CourierInvoiceLine> CourierInvoiceLines { get; set; } = new List<CourierInvoiceLine>();
}