// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierSchedule
{
    public long Id { get; set; }

    public DateTime Created { get; set; }

    public DateTime BookDate { get; set; }

    public int? SiteId { get; set; }

    public string Name { get; set; }

    public DateTime? NotificationSent { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public int Wanted { get; set; }

    public int? LocationId { get; set; }

    public virtual ICollection<CourierScheduleResponse> CourierScheduleResponses { get; set; } = new List<CourierScheduleResponse>();

    public virtual TblBulkRegion Location { get; set; }
}