// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierInvoiceLineJobMaster
{
    public long Id { get; set; }

    public long LineId { get; set; }

    public int JobId { get; set; }

    public virtual CourierInvoiceLine Line { get; set; }
}