// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierScheduleTimeSlotVehicleType
{
    public long Id { get; set; }

    public DateTime Created { get; set; }

    public long TimeSlotId { get; set; }

    public int VehicleTypeId { get; set; }

    public virtual CourierScheduleTimeSlot TimeSlot { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}