// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierScheduleResponseStatus
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<CourierScheduleResponse> CourierScheduleResponseNotificationStatuses { get; set; } = new List<CourierScheduleResponse>();

    public virtual ICollection<CourierScheduleResponse> CourierScheduleResponseStatuses { get; set; } = new List<CourierScheduleResponse>();
}