// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class CourierApplicantDocument
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public string Name { get; set; }

    public string Instructions { get; set; }

    public bool Mandatory { get; set; }

    public bool Active { get; set; }

    public string FileName { get; set; }

    public string Type { get; set; }

    public long? Length { get; set; }

    public byte[] Data { get; set; }

    public virtual ICollection<CourierApplicantUpload> CourierApplicantUploads { get; set; } = new List<CourierApplicantUpload>();
}