// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class InfringementCategoryLink
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Link { get; set; }

    public bool Active { get; set; }

    public virtual InfringementCategory Category { get; set; }
}