// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class PaymentTerm
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public string Name { get; set; }

    public int Days { get; set; }

    public virtual ICollection<TblSetting> TblSettingCourierInvoiceBatchPaymentTerms { get; set; } = new List<TblSetting>();

    public virtual ICollection<TblSetting> TblSettingPaymentTerms { get; set; } = new List<TblSetting>();

    public virtual ICollection<TucClient> TucClients { get; set; } = new List<TucClient>();
}