// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class TblBulkRegion
{
    public int BulkRegionId { get; set; }

    public string Name { get; set; }

    public string FromCompany { get; set; }

    public string FromAddress { get; set; }

    public string FromSuburb { get; set; }

    public int FromPostCode { get; set; }

    public decimal? PickupLatitude { get; set; }

    public decimal? PickupLongitude { get; set; }

    public bool Active { get; set; }

    public bool? RunScanWebhook { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string AccountsCode { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string AddressLine4 { get; set; }

    public string AddressLine5 { get; set; }

    public string AddressLine6 { get; set; }

    public string AddressLine7 { get; set; }

    public string AddressLine8 { get; set; }

    public bool? CourierApplicantEnabled { get; set; }

    public virtual ICollection<CourierApplicant> CourierApplicants { get; set; } = new List<CourierApplicant>();

    public virtual ICollection<CourierScheduleTimeSlot> CourierScheduleTimeSlots { get; set; } = new List<CourierScheduleTimeSlot>();

    public virtual ICollection<CourierSchedule> CourierSchedules { get; set; } = new List<CourierSchedule>();

    public virtual ICollection<TucCourier> TucCouriers { get; set; } = new List<TucCourier>();
}