// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class TblReport
{
    public int ReportId { get; set; }

    public string Object { get; set; }

    public string Name { get; set; }

    public string Style { get; set; }

    public string ReportName { get; set; }

    public string Description { get; set; }

    public string HeaderText { get; set; }

    public string FilterDate { get; set; }

    public string FilterCourier { get; set; }

    public string FilterClient { get; set; }

    public string FilterDespatcher { get; set; }

    public string FilterClientType { get; set; }

    public string FilterGroupBy { get; set; }

    public string FilterPercentage { get; set; }

    public bool EnablePreview { get; set; }

    public bool EnableOptions { get; set; }

    public string CustomPage { get; set; }

    public int? CustomPageWidth { get; set; }

    public int? CustomPageHeight { get; set; }

    public string CustomPageWindowFeatures { get; set; }

    public string WhereCondition { get; set; }

    public string CustomParameter1 { get; set; }

    public string CustomParameter2 { get; set; }

    public string CustomParameter3 { get; set; }

    public int ReportFormatId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string FilterAccountProfile { get; set; }

    public string FilterYearMonth { get; set; }

    public bool Active { get; set; }

    public string FilterSite { get; set; }

    public virtual ICollection<TblSetting> TblSettingInternetInvoiceReports { get; set; } = new List<TblSetting>();

    public virtual ICollection<TblSetting> TblSettingInternetRateScheduleReports { get; set; } = new List<TblSetting>();

    public virtual ICollection<TblUserGroupReport> TblUserGroupReports { get; set; } = new List<TblUserGroupReport>();
}