// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class TblUserGroupReport
{
    public int UserGroupId { get; set; }

    public int ReportId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public virtual TblReport Report { get; set; }
}