// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CourierPortal.Core.Domain.Entities;

public partial class VehicleType
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public string Name { get; set; }

    public virtual ICollection<CourierScheduleTimeSlotVehicleType> CourierScheduleTimeSlotVehicleTypes { get; set; } = new List<CourierScheduleTimeSlotVehicleType>();
}